SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t
    ON i.ITEM_ID = t.ITEM_ID
JOIN ITEM_INFO parent
    ON t.PARENT_ITEM_ID = parent.ITEM_ID
WHERE parent.RARITY = 'RARE'
ORDER BY i.ITEM_ID DESC;